### PR TITLE
[ADD] Migrated base_module_record in v11

### PR DESCRIPTION
**Pull request by sudhir-serpentcs**
Migrated base_module_record in v11.
Removed YAML related code.

**Pending improvements:** 
1: Remove frozendict and use with_context({})
2: Binary fields makes the execution very slow. Maybe we can skip the binary fields during data generation for faster execution.

@JayVora-SerpentCS Please review.

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
.po files too need to be updated.

**Comment by sudhir-serpentcs** [comment]
>  JayVora-SerpentCS commented 17 hours ago .po files too need to be updated.

.po files? Sorry I don't see any po file in the module. Can you please tell me exactly where is it?
@JayVora-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
Isn't there any? If no, then skip.

**Comment by JayVora-SerpentCS** [comment]
Please fix some travis, as it links to this module

**Comment by sudhir-serpentcs** [comment]
@JayVora-SerpentCS Improved the code to pass the context as per the standard, removed unused objects and code. Please review and merge.
Travis is failing because of other modules.

**Comment by JayVora-SerpentCS** [comment]
Please check https://travis-ci.org/JayVora-SerpentCS/SerpentCS_Contributions/jobs/292020895#L1039

**Pull request merged**
