### PR TITLE
[15.0][MIG] sale_restrict :Migrated Module

### PR DESCRIPTION
**Pull request by ilakkia-serpentcs**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@tushar-serpentcs review with v15 exisitng features always.

**Comment by tushar-serpentcs** [comment]
@JayVora-SerpentCS PR Reviewed

**Comment by ketanserpentcs** [comment]
This PR Testing has been completed  by Siddharaj.

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@JayVora-SerpentCS  Ready to merge

**Pull request merged**
