### PR TITLE
[14.0] [MIG] partner_credit_limit: Module migrated in v14. (Ready to test)

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS plz use the tag (WIP, ready to test, in QA, ready to merge)

**Comment by Chandresh-SerpentCS** [comment]
PR is **`Ready For Test`** now.

**Comment by Savitri-SerpentCS** [comment]
@JayVora-SerpentCS sir , i have tested this module in november 2020 and also shared the defectsheet with @Chandresh-SerpentCS sir. But didn't get any revert back. Once issues will be fixed from developer side,i will retest it.

**Comment by JayVora-SerpentCS** [comment]
@Savitri-SerpentCS merged this now. remove from QA list.

**Pull request merged**
