### PR TITLE
[MIG] [17.0] sales_report_product_image: migrated module

### PR DESCRIPTION
**Pull request by ShwetaSerpentCS**
Responsible : **Neel**

### CODE REVIEW

**Review by Trivedi-Vacha-SerpentCS — APPROVED** [review]

**Comment by ketanserpentcs** [comment]
Testing is assigned to Devraj

**Comment by ShwetaSerpentCS** [comment]
Testing is done by Devraj. 

Please merge this PR. @Trivedi-Vacha-SerpentCS 

cc: @ketanserpentcs

**Comment by ketanserpentcs** [comment]
Testing has been done by devraj
@ShwetaSerpentCS , Please change label QA done

**Comment by ShwetaSerpentCS** [comment]
> Testing has been done by devraj @ShwetaSerpentCS , Please change label QA done

I'm not able to add or remove label. so please do the needful.

Thank you. @ketanserpentcs

**Pull request merged**
