### PR TITLE
[15.0][MIG] hr_applicant: Migrated module

### PR DESCRIPTION
**Pull request by Trivedi-Vacha-SerpentCS**
Developed by @Ilakkia
Ready for QA

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@Trivedi-Vacha-SerpentCS good to go ?

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> @Trivedi-Vacha-SerpentCS good to go ?

Ready for QA

**Comment by JayVora-SerpentCS** [comment]
@ketan-serpentcs

**Comment by ketanserpentcs** [comment]
Testing Assigned to Siddharaj.

**Comment by JayVora-SerpentCS** [comment]
Siddhraj pase thi koi update?

**Comment by ketanserpentcs** [comment]
Tested and assigned to developer for issues fixing.

**Comment by JayVora-SerpentCS** [comment]
@ilakkia-serpentcs  ?

**Comment by ilakkia-serpentcs** [comment]
@Jay sir - hr_applicant defect sheet  issues fixed sir

**Comment by JayVora-SerpentCS** [comment]
@Trivedi-Vacha-SerpentCS should I proceed? Need your pro signal!

**Comment by Trivedi-Vacha-SerpentCS** [comment]
Ready to merge @JayVora-SerpentCS

**Pull request merged**
