### PR TITLE
[14.0] [MIG] sale_restrict: Module migrated in v14. (Ready to test)

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
tag please.

**Comment by Chandresh-SerpentCS** [comment]
PR is **`Ready For Test`** now.

**Comment by JayVora-SerpentCS** [comment]
Ping

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS seems this is an immense ignorance.

**Comment by Chandresh-SerpentCS** [comment]
PR is ready to test by testing team.

**Comment by JayVora-SerpentCS** [comment]
Is it given to a QA guy? no followup taken it seems.

**Comment by Chandresh-SerpentCS** [comment]
Yes, I already talked with Ketanbhai for this, and I guess It is also assigned to Savitri to test the PRs.

**Comment by Savitri-SerpentCS** [comment]
@JayVora-SerpentCS sir , i have tested this module in november 2020 and also shared the defectsheet with @Chandresh-SerpentCS sir. But didn't get any revert back.Once issues will be fixed from developer side,i will retest it.

**Comment by JayVora-SerpentCS** [comment]
@Chandresh-SerpentCS please update

**Comment by Chandresh-SerpentCS** [comment]
I will check and update here. Thank you.

**Comment by Chandresh-SerpentCS** [comment]
@Savitri-SerpentCS PR is ready to test.

**Comment by Savitri-SerpentCS** [comment]
@Chandresh-SerpentCS sir, Sale_Restrict V14 testing has been completed with latest code.

**Comment by Chandresh-SerpentCS** [comment]
@JayVora-SerpentCS sir, Please merge this PR.

**Pull request merged**
