### PR TITLE
[FIX] Synchronize Date. Logging.

### PR DESCRIPTION
**Pull request by sebastiken**
Field synchronize_date is not being writed, so always made full synchronization.
Add logging messages to wizard in DEBUG level.

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
Did you mean base_synchro/base_synchro_obj.py file is not used?
IMHO, it is used for the models.

**Comment by sebastiken** [comment]
@JayVora-SerpentCS yes, in branch *8.0* it is not used anymore. Instead _models/base_synchro_obj.py_ is used and imported from *__init__.py* inside _models_ directory. And _models_ is imported by *__init__.py* of _base_synchro_ directory.
I hope you understand me. The module is really great, thanks!.

**Comment by JayVora-SerpentCS** [comment]
Indeed, you are right!
I am merging this PR. Would you be able to work on some travis fixes please?

**Comment by sebastiken** [comment]
Yes, I will fix to pass Travis. Don't worry.

**Pull request merged**
