### PR TITLE
[15.0][MIG]base_module_record: Migrated the module from v14 to v15

### PR DESCRIPTION
**Pull request by ShivamS-SerpentCS**
- Fixed the "Invalid fields None on model account.tax.repartition.line" while recording the res.partner model.

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@ketan-serpentcs pls add a QA member

**Comment by ketanserpentcs** [comment]
> @ketan-serpentcs pls add a QA member

I have assigned to INAM for [15.0][MIG]base_module_record testing

**Comment by JayVora-SerpentCS** [comment]
@ketanserpentcs update plz

**Comment by ketanserpentcs** [comment]
> @ketanserpentcs update plz

Testing has been completed by Inam

**Comment by ShwetaSerpentCS** [comment]
> > @ketanserpentcs update plz
> 
> Testing has been completed by Inam

@JayVora-SerpentCS Please review & merge it.

Thanks.

**Pull request merged**
