### PR TITLE
[IMP] ipushp : Improved validations in backend , frontend ,fixed errors.

### PR DESCRIPTION
**Pull request by warlock-workspace**
Solved Defect-sheet Issues 

Tested by :- Pooja Patel

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@Murtaza-SerpentCS You have to pass it to Bhavesh to see it. its his PR

**Comment by Vandan-Pandeji-SerpentCS** [comment]
@Murtaza-SerpentCS Gentle reminder!

**Comment by ketanserpentcs** [comment]
Testing has been done by Pooja

**Comment by Bhavesh-SCS** [comment]
Related to this PR , The code has already been merged with main branch (JayVora-SerpentCS/SerpentCS_Contributions) ,
So we dont need to merge this PR , we can safely close this PR.

**Comment by Trivedi-Vacha-SerpentCS** [comment]
Closing the PR as the changes already moved in the  module.
cc @ShwetaSerpentCS

**Pull request closed without merging**
