### PR TITLE
[FIX]web_groupby_expand:fixed issue of pager in group by in tree view

### PR DESCRIPTION
**Pull request by nikitavaghela**
fixed issue showed in this link: https://github.com/JayVora-SerpentCS/SerpentCS_Contributions/issues/280#issuecomment-437833110

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@hpatelserpentcs @nikul-serpentcs

**Comment by hpatelserpentcs** [comment]
@JayVora-SerpentCS 

Hello sir,

This improvement is proper you can merge it.

**Comment by nikul-serpentcs** [comment]
@JayVora-SerpentCS @nikitavaghela Please review the JS linter, though.

https://travis-ci.org/JayVora-SerpentCS/SerpentCS_Contributions/jobs/454417810#L1881

**Comment by JayVora-SerpentCS** [comment]
@nikitavaghela please check

**Pull request merged**
