### PR TITLE
[12.0][ADD] base_module_record:fixed the issue and improved manifest …

### PR DESCRIPTION
**Pull request by ChavdaRiddhi**
…file.

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
are these travis fixes?

**Comment by ChavdaRiddhi** [comment]
@JayVora-SerpentCS 
There was some problem in travis. so i will check and update you as soon as possible.

**Comment by JayVora-SerpentCS** [comment]
Check and tell me

**Comment by RiddhiChavda22** [comment]
@JayVora-SerpentCS 
travis of this module was fixed.

**Comment by ChavdaRiddhi** [comment]
@JayVora-SerpentCS 
travis of this module was fixed.

**Pull request merged**
