### PR TITLE
[IMP]website_multi_image_zoom: Solved the issue of double images were  being displayed in zoom lense when user try to zoom image of any product.

### PR DESCRIPTION
**Pull request by drashtipatel24**
Solved the issue of double images were  being displayed in zoom lense when user try to zoom image of any product.

### CODE REVIEW

**Comment by parvezqureshi** [comment]
1)ERROR:
When we upload image in multi_image one2many field but did not save it and click on List All Image button, it gives me below error:

Odoo Server Error
Traceback (most recent call last):
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/serpentcs/workspace/openerp/odoo_10/addons/web/controllers/main.py", line 827, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/home/serpentcs/workspace/openerp/odoo_10/addons/web/controllers/main.py", line 849, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/models.py", line 4679, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/models.py", line 1518, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/models.py", line 4242, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/serpentcs/workspace/openerp/odoo_10/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for integer: "one2many_v_id_67"
LINE 1: ...ROM "multi_images" WHERE ("multi_images"."id" in ('one2many_...

2) I uploaded 2 image in multi_image one2many field  and save it,then I tried to add 3rd image in multi_image one2many field but did not saved it and click on image preview button,then it shows me below alert:

"Please Save the record when you are adding an image for the first time !!"

My suggestion is that when no record id is found,then above alert should be displayed.

Suppose 2 image record ids found and 3rd image record id not found then no alert given instead of 2 image record should be displayed on preview.

**Comment by ghost** [comment]
@drashtipatel24 Can you please add separate pull request for each module ? Please look into the error @parvezqureshi mentioned.

**Comment by JayVora-SerpentCS** [comment]
Let me know if this is ready to get merged

**Comment by ghost** [comment]
@JayVora-SerpentCS Travis shows error messages which are not related to this changes.

**Pull request merged**
