### PR TITLE
[15.0][MIG] partner_credit_limit

### PR DESCRIPTION
**Pull request by Freni-SerpentCS**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
Has this been given to QA? @Freni-SerpentCS ?

**Comment by Freni-OSI** [comment]
> Has this been given to QA? @Freni-SerpentCS ?

Yes Sir, just gave it to Ketan sir.

**Comment by Savitri-SerpentCS** [comment]
1st phase of testing is completed by siddharaj. Now issues are pending to fix by developer.

**Comment by JayVora-SerpentCS** [comment]
@Freni-SerpentCS !

**Comment by ShwetaSerpentCS** [comment]
@JayVora-SerpentCS Can you please merge this PR? So we can process next.

Thank You.

**Pull request merged**
