### PR TITLE
[MIG][16.0] project_team: Migrated the module.

### PR DESCRIPTION
**Pull request by PratikVaza-SerpentCS**
**Migrated By: Dhairya Popat**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
Do we need this in v16 @PratikVaza-SerpentCS ?

**Comment by JayVora-SerpentCS** [comment]
@urvisha-serpentCS pls see

**Review by urvisha-serpentcs — APPROVED** [review]

**Comment by Trivedi-Vacha-SerpentCS** [comment]
Discussed with @ketan, QA has been not done for this.
@JayVora-SerpentCS can merge once QA cleared.

**Comment by Trivedi-Vacha-SerpentCS** [comment]
QA cleared by Pooja Patel.
@JayVora-SerpentCS Sir can you please merge?

**Pull request merged**
