### PR TITLE
[15.0][IMP]ipushup: fix the travis issue

### PR DESCRIPTION
**Pull request by ilakkia-serpentcs**

### CODE REVIEW

**Comment by JayVora-SerpentCS** [comment]
@Dhirendrasinh-SerpentCS pls review. Speially js

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@Dhirendrasinh-SerpentCS Can you please fix the remaining travis issue regarding .js files?

**Comment by Dhirendrasinh-SerpentCS** [comment]
@Trivedi-Vacha-SerpentCS Ma'am
travis issue regarding .js has been done in this PR: #589

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@JayVora-SerpentCS Need quick merge of this PR for another bug fix to avoid conflict.

**Pull request merged**
