### PR TITLE
[MIG] [18.0] project_detail_report: migrated module

### PR DESCRIPTION
**Pull request by ShwetaSerpentCS**
Responsible : Jayram

### CODE REVIEW

**Comment by ketanserpentcs** [comment]
Testing is assigned to Devraj

**Comment by ketanserpentcs** [comment]
QA done with index by Devraj

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@ShwetaSerpentCS kindly verify index and banner

**Comment by ShwetaSerpentCS** [comment]
> @ShwetaSerpentCS kindly verify index and banner

Index, Banner both done. Kindly merge this PR.

Thanks. @Trivedi-Vacha-SerpentCS

**Comment by JayVora-SerpentCS** [comment]
As Vacha n Shweta both r seniors here : I expect that you both thought well enough to make change in report, make it look beautiful, better than earlier.
I will merge now, but keep this in loop. we wnt better version.

**Pull request merged**
