### PR TITLE
[14.0] [MIG] sales_report_product_image: Migrated the module in v14.

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**
- Module developed by **Pragati Patel**. (Assigned by **Yogesh Mahera**)

### CODE REVIEW

**Comment by Chandresh-SerpentCS** [comment]
@YogeshMahera-SerpentCS Please review the PR. Thanks.

**Comment by JayVora-SerpentCS** [comment]
Do we really need this module?
@YogeshMahera-SerpentCS think with image_1920 concept in v14.

**Comment by JayVora-SerpentCS** [comment]
Ping!

**Comment by Chandresh-SerpentCS** [comment]
Ping @YogeshMahera-SerpentCS

**Comment by YogeshMahera-SerpentCS** [comment]
I think this module specification like User will be able to print the image of the product in SalesOrder/Quotation and technically we've used the image_1920 field from the product.

Normally users are not able to print the image of products in sale order. so this module provides allows print with the image of products in SaleOrder/Quotations. And I think we need to keep this module.

**Comment by JayVora-SerpentCS** [comment]
Does our module handle the access control too?
Ask the QA team to run a scenario with non admin simple salesman who access his own records, to print it.

**Comment by YogeshMahera-SerpentCS** [comment]
Assigned to QA Team(Savitri)

**Pull request merged**
