### PR TITLE
[16.0] [MIG] Migrated web_digital_sign

### PR DESCRIPTION
**Pull request by dhaval-serpentcs**

### CODE REVIEW

**Comment by Vandan-Pandeji-SerpentCS** [comment]
LGTM.

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> LGTM.

Are we good to merge? QA pass?

**Comment by ketanserpentcs** [comment]
Testing is assigned to Pooja

**Comment by Vandan-Pandeji-SerpentCS** [comment]
I manually tested the code and discovered that JavaScript isn't functioning as expected.
CC @Trivedi-Vacha-SerpentCS @ketanserpentcs @ShwetaSerpentCS

**Comment by Trivedi-Vacha-SerpentCS** [comment]
@ShwetaSerpentCS should we close this PR? as new PR is already merged.

**Comment by ShwetaSerpentCS** [comment]
> @ShwetaSerpentCS should we close this PR? as new PR is already merged.

yes we can close this PR @Trivedi-Vacha-SerpentCS

**Comment by Trivedi-Vacha-SerpentCS** [comment]
Closing this PR as pr #642 ha latest updates

**Pull request closed without merging**
